---
jobs:
- name: job-build-task-image
  public: true
  serial: true
  plan:
  - get: pipeline
    resource: git-pipeline-docker-image
    trigger: true
  - put: docker-image
    params:
      build: pipeline/ci_image

resources:
- name: git-pipeline-docker-image
  type: git
  source:
    uri: git@github.com:drnic/redis-bosh-pipeline.git
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}
    paths: [ci_image/*]

- name: docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-create-hub-task-image}}
