FROM concourse/concourse-ci
# https://github.com/concourse/concourse/blob/master/ci/dockerfiles/concourse-ci/Dockerfile

ADD spiff-merge-and-save /bin/spiff-merge-and-save
ADD git-add-stage-changes /bin/git-add-stage-changes
