compilation:
  cloud_properties:
    name: random
  network: redis1
  reuse_compilation_vms: true
  workers: 6
director_uuid: 9c7ca635-f6e5-43c3-a795-87ad19388cb9
jobs:
- instances: 1
  name: redis_leader_z1
  networks:
  - name: redis1
    static_ips:
    - 10.244.16.2
  persistent_disk: 4096
  properties:
    network: redis1
    redis:
      password: production
  resource_pool: small_z1
  templates:
  - name: redis
    release: redis
- instances: 1
  name: redis_z1
  networks:
  - name: redis1
    static_ips: null
  persistent_disk: 4096
  properties:
    network: redis1
    redis:
      master: 10.244.16.2
      password: production
  resource_pool: small_z1
  templates:
  - name: redis
    release: redis
  update:
    canaries: 10
- instances: 1
  name: redis_test_slave_z1
  networks:
  - name: redis1
    static_ips:
    - 10.244.16.6
  persistent_disk: 4096
  properties:
    network: redis1
    redis:
      master: 10.244.16.2
      password: production
  resource_pool: small_z1
  templates:
  - name: redis
    release: redis
- instances: 1
  lifecycle: errand
  name: acceptance-tests
  networks:
  - name: redis1
    static_ips: null
  properties:
    redis:
      master: 10.244.16.2
      password: production
      slave: 10.244.16.6
  resource_pool: small_z1
  templates:
  - name: acceptance-tests
    release: redis
meta:
  environment: null
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: 2776
name: redis-prod
networks:
- name: redis1
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.16.0/30
    reserved:
    - 10.244.16.1
    static:
    - 10.244.16.2
  - cloud_properties:
      name: random
    range: 10.244.16.4/30
    reserved:
    - 10.244.16.5
    static:
    - 10.244.16.6
  - cloud_properties:
      name: random
    range: 10.244.16.8/30
    reserved:
    - 10.244.16.9
    static: []
  - cloud_properties:
      name: random
    range: 10.244.16.12/30
    reserved:
    - 10.244.16.13
    static: []
  - cloud_properties:
      name: random
    range: 10.244.16.16/30
    reserved:
    - 10.244.16.17
    static: []
  - cloud_properties:
      name: random
    range: 10.244.16.20/30
    reserved:
    - 10.244.16.21
    static: []
  - cloud_properties:
      name: random
    range: 10.244.16.24/30
    reserved:
    - 10.244.16.25
    static: []
  - cloud_properties:
      name: random
    range: 10.244.16.28/30
    reserved:
    - 10.244.16.29
    static: []
properties:
  redis: {}
releases:
- name: redis
  version: 9.1
resource_pools:
- cloud_properties:
    name: random
  name: small_z1
  network: redis1
  size: 4
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: 2776
update:
  canaries: 1
  canary_watch_time: 1000-100000
  max_in_flight: 50
  update_watch_time: 1000-100000

