meta:
  environment: redis-aws
  security_groups: (( merge ))

  stemcell:
    name: bosh-aws-xen-ubuntu-trusty-go_agent
    version: latest

  persistent_disk: 4096

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-100000
  update_watch_time: 1000-100000

jobs:
  - name: redis_leader_z1
    instances: 1
    networks:
      - name: redis1
        static_ips: ~
    persistent_disk: (( meta.persistent_disk ))
  - name: redis_z1
    networks:
      - name: redis1
        static_ips: ~
    persistent_disk: (( meta.persistent_disk ))
    properties:
      redis:
        master: (( "0.redis-leader-z1.redis1." meta.environment ".microbosh" ))
      network: redis1
  - name: redis_test_slave_z1
    networks:
      - name: redis1
        static_ips: ~
    persistent_disk: (( meta.persistent_disk ))
    properties:
      redis:
        master: (( "0.redis-leader-z1.redis1." meta.environment ".microbosh" ))
      network: redis1
  - name: acceptance-tests
    networks:
      - name: redis1
    properties:
      redis:
        master: (( "0.redis-leader-z1.redis1." meta.environment ".microbosh" ))
        slave: (( "0.redis-test-slave-z1.redis1." meta.environment ".microbosh" ))

compilation:
  cloud_properties:
    instance_type: m1.small

resource_pools:
  - name: small_z1
    cloud_properties:
      instance_type: m1.small

networks:
  - name: floating
    type: vip
    cloud_properties: {}
  - name: redis1
    type: dynamic
    cloud_properties:
      security_groups: (( meta.security_groups ))
